// MSI Assistant — Cloudflare Worker
// POST /chat  { messages:[{role:"user"|"assistant", content:"..."}], context:{app, line, model, symptom} }
//          -> { reply:"..." }
// Secrets / variables (Worker > Settings > Variables and Secrets):
//   ANTHROPIC_API_KEY  (secret, required)
//   MODEL              (optional, default below)
//   ALLOWED_ORIGINS    (optional, comma-separated; defaults below)
// Knowledge is generated by build_knowledge.py — do not edit the KB line by hand.

const KB = /*KNOWLEDGE*/null;

const DEFAULT_MODEL = "claude-sonnet-5";
const DEFAULT_ORIGINS = [
  "https://msi.adam-wade.workers.dev",
  "https://msitroubleshooting.com",
  "https://www.msitroubleshooting.com",
];
const MAX_TURNS = 12, MAX_CHARS = 2000, TOP_K = 8, CONTEXT_BUDGET = 16000;
const RATE = { windowMs: 10 * 60 * 1000, max: 30 };

// ---------- retrieval (BM25) ----------
const STOP = new Set("a an and are as at be by can do does for from has have how i if in is it its my of on or so that the this to was what when where which why with you your our we me not no".split(" "));
const tok = s => (s.toLowerCase().match(/[a-z0-9µ±.\-]+/g) || [])
  .map(w => w.replace(/^[.\-]+|[.\-]+$/g, "")).filter(w => w.length > 1 && !STOP.has(w))
  .map(w => w.length > 4 ? w.replace(/(ing|ed|es|s)$/, "") : w);

let INDEX = null;
function buildIndex() {
  const docs = KB.chunks.map(c => {
    const t = tok(c.title + " " + c.title + " " + c.text);   // title counted twice
    const tf = new Map(); t.forEach(w => tf.set(w, (tf.get(w) || 0) + 1));
    return { c, tf, len: t.length };
  });
  const df = new Map();
  docs.forEach(d => d.tf.forEach((_, w) => df.set(w, (df.get(w) || 0) + 1)));
  const avg = docs.reduce((s, d) => s + d.len, 0) / docs.length;
  return { docs, df, avg, N: docs.length };
}
function search(query, app) {
  INDEX ||= buildIndex();
  const { docs, df, avg, N } = INDEX, q = [...new Set(tok(query))], k1 = 1.4, b = 0.75;
  return docs.map(d => {
    let s = 0;
    for (const w of q) {
      const f = d.tf.get(w); if (!f) continue;
      const idf = Math.log(1 + (N - df.get(w) + 0.5) / (df.get(w) + 0.5));
      s += idf * (f * (k1 + 1)) / (f + k1 * (1 - b + b * d.len / avg));
    }
    if (app && d.c.app === app) s *= 1.6;          // prefer the troubleshooter the user is in
    return { s, c: d.c };
  }).filter(x => x.s > 0).sort((a, b) => b.s - a.s).slice(0, TOP_K).map(x => x.c);
}

// ---------- prompt ----------
function systemPrompt() {
  const products = KB.products.map(p =>
    `### ${p.product} — brand: ${p.brand}; service contact: ${p.support}\nKnown symptoms (name -> troubleshooter link):\n` +
    p.symptoms.map(s => "- " + s).join("\n")).join("\n\n");
  return `You are the Machine Solutions Assistant on the Machine Solutions equipment troubleshooting site. You help operators, process engineers and maintenance staff at medical device manufacturers diagnose problems on Machine Solutions equipment, and answer general questions about Machine Solutions and its brands.

HOW TO ANSWER
- Base every technical answer ONLY on the reference material provided in the "Reference material" block for this turn and the product list below. If the answer isn't there, say so plainly and direct the person to the right support contact. Never invent settings, values, part numbers, screen names or procedures.
- Work like a good field service engineer: if the symptom is unclear, ask one short clarifying question (which machine or model, what the part looks like, the exact HMI/error message). Otherwise give the likely causes in the order the guide lists them, with the checks or adjustments for each, and suggest changing one thing at a time.
- Always include any SAFETY notes from the reference material that apply to the steps you give.
- When a cause is marked as requiring a service technician, never describe how to do it; tell the person to contact the listed service contact and mention the cause.
- Never advise bypassing guards, interlocks, safety circuits, or alarms, opening electrical enclosures, or operating equipment outside its manual. If someone is hurt, or there is smoke, fire, or an electrical hazard, tell them to stop, make the machine safe per site procedures, and get help immediately.
- Link to the matching troubleshooter page using the exact links given (markdown, e.g. [Braid bunching at high PPI](/braiding/#braider/…)) so they can follow the step-by-step guide with pictures.
- For quotes, pricing, new equipment, lab time or anything commercial, point them to sales@machinesolutions.com. Do not quote prices or commit to delivery, warranty or repairs.
- Voice: confident, precise, collaborative (Machine Solutions brand voice). Keep answers short and scannable for a phone on the shop floor: a sentence of orientation, then short numbered steps. Include units on all measurements.
- Reply in the language the person writes in.
- You are an AI assistant. If asked, say so, and remind people that the operator manual and their site's procedures take precedence.
- Stay on topic: Machine Solutions equipment, processes and company information. Politely decline anything else.

PRODUCTS COVERED BY TROUBLESHOOTERS
${products}

GENERAL CONTACTS
Machine Solutions, 2951 W. Shamrell Blvd. Suite 107, Flagstaff, AZ 86005 USA · main 928-556-3109 · info@machinesolutions.com · sales@machinesolutions.com · MSI Service service@machinesolutions.com · website https://www.machinesolutions.com`;
}
let SYSTEM = null;

function contextBlock(chunks, ctx) {
  let out = "", used = 0;
  for (const c of chunks) {
    const block = `\n[${c.title}] (link: ${c.url})\n${c.text}\n`;
    if (used + block.length > CONTEXT_BUDGET) break;
    out += block; used += block.length;
  }
  const where = ctx && ctx.app ? `The person is currently in the ${ctx.app} troubleshooter` +
    (ctx.model ? `, machine model: ${ctx.model}` : "") + (ctx.symptom ? `, looking at: "${ctx.symptom}"` : "") + ".\n" : "";
  return `${where}Reference material for this turn:\n${out || "(no matching material found)"}`;
}

// ---------- http ----------
const hits = new Map();
function limited(ip) {
  const now = Date.now(), h = (hits.get(ip) || []).filter(t => now - t < RATE.windowMs);
  h.push(now); hits.set(ip, h);
  if (hits.size > 5000) hits.clear();
  return h.length > RATE.max;
}
function cors(origin, env) {
  const allowed = (env.ALLOWED_ORIGINS ? env.ALLOWED_ORIGINS.split(",").map(s => s.trim()) : DEFAULT_ORIGINS);
  const ok = allowed.includes(origin) || /^http:\/\/localhost(:\d+)?$/.test(origin || "");
  return ok ? { "Access-Control-Allow-Origin": origin, "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type", "Access-Control-Max-Age": "86400", "Vary": "Origin" } : null;
}
const json = (obj, status, h) => new Response(JSON.stringify(obj), { status, headers: { "Content-Type": "application/json", ...(h || {}) } });

export default {
  async fetch(req, env) {
    const url = new URL(req.url), origin = req.headers.get("Origin"), ch = cors(origin, env);
    if (url.pathname === "/health") return json({ ok: true, chunks: KB.chunks.length }, 200, ch || {});
    if (req.method === "OPTIONS") return new Response(null, { status: ch ? 204 : 403, headers: ch || {} });
    if (url.pathname !== "/chat" || req.method !== "POST") return json({ error: "not found" }, 404, ch || {});
    if (!ch) return json({ error: "origin not allowed" }, 403);
    if (!env.ANTHROPIC_API_KEY) return json({ error: "assistant not configured" }, 500, ch);
    if (limited(req.headers.get("CF-Connecting-IP") || "anon"))
      return json({ error: "Too many questions in a short time. Please wait a few minutes and try again." }, 429, ch);

    let body;
    try { body = await req.json(); } catch { return json({ error: "bad request" }, 400, ch); }
    let msgs = Array.isArray(body.messages) ? body.messages : [];
    msgs = msgs.filter(m => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string" && m.content.trim())
      .map(m => ({ role: m.role, content: m.content.slice(0, MAX_CHARS) })).slice(-MAX_TURNS);
    while (msgs.length && msgs[0].role !== "user") msgs.shift();
    if (!msgs.length || msgs[msgs.length - 1].role !== "user") return json({ error: "bad request" }, 400, ch);
    const ctx = body.context && typeof body.context === "object" ? {
      app: String(body.context.app || "").slice(0, 40), model: String(body.context.model || "").slice(0, 80),
      symptom: String(body.context.symptom || "").slice(0, 200) } : {};

    const users = msgs.filter(m => m.role === "user").map(m => m.content);
    const query = users.slice(-2).join(" ") + " " + (ctx.symptom || "") + " " + (ctx.model || "");
    const chunks = search(query, ctx.app);
    SYSTEM ||= systemPrompt();

    const r = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "x-api-key": env.ANTHROPIC_API_KEY, "anthropic-version": "2023-06-01", "content-type": "application/json" },
      body: JSON.stringify({
        model: env.MODEL || DEFAULT_MODEL, max_tokens: 1000,
        system: [
          { type: "text", text: SYSTEM, cache_control: { type: "ephemeral" } },
          { type: "text", text: contextBlock(chunks, ctx) },
        ],
        messages: msgs,
      }),
    });
    if (!r.ok) {
      console.log("anthropic error", r.status, (await r.text()).slice(0, 500));
      return json({ error: "The assistant is unavailable right now. Please try again, or contact service@machinesolutions.com." }, 502, ch);
    }
    const data = await r.json();
    const reply = (data.content || []).filter(b => b.type === "text").map(b => b.text).join("\n").trim();
    return json({ reply: reply || "Sorry, I couldn't produce an answer. Please rephrase or contact service@machinesolutions.com." }, 200, ch);
  },
};
